name: kubaby
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: 2.0.4
  gap: 2.0.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  table_calendar: 3.0.9
  collection: 1.17.0
  path_provider:
  cached_network_image: ^3.2.3
  # intl: ^0.17.0
  intl:
  google_fonts: 4.0.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  build_runner: 2.3.3
  json_serializable: 6.6.1
  flutter_gen_runner: 5.2.0
  hive_generator: 2.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/

flutter_gen:
  output: lib/app/config/
